import type { Phoneme, WordEntry } from '../../../types/phonetics'

/**
 * Placeholder content for the Phase 1 prototype only — NOT the final curated
 * pedagogical phoneme table (that needs review with a teacher, see the project
 * plan). Deliberately includes more phoneme tiles than the sample words use,
 * so the "grayed out dead-end tile" behavior has something to demonstrate.
 */
export const samplePhonemes: Phoneme[] = [
  { id: 'a', displaySymbol: 'a', graphemes: [{ grapheme: 'a', exampleWord: 'chat' }], order: 1, level: 'both' },
  { id: 'e', displaySymbol: 'é', graphemes: [{ grapheme: 'é', exampleWord: 'vélo' }], order: 2, level: 'both' },
  { id: 'i', displaySymbol: 'i', graphemes: [{ grapheme: 'i', exampleWord: 'lion' }], order: 3, level: 'both' },
  { id: 'o', displaySymbol: 'o', graphemes: [{ grapheme: 'o', exampleWord: 'moto' }, { grapheme: 'eau', exampleWord: 'bateau' }], order: 4, level: 'both' },
  { id: 'u', displaySymbol: 'u', graphemes: [{ grapheme: 'u', exampleWord: 'tortue' }], order: 5, level: 'both' },
  { id: 'ou', displaySymbol: 'ou', graphemes: [{ grapheme: 'ou', exampleWord: 'souris' }], order: 6, level: 'both' },
  { id: 'on', displaySymbol: 'on', graphemes: [{ grapheme: 'on', exampleWord: 'ballon' }], order: 7, level: 'both' },
  { id: 'an', displaySymbol: 'an', graphemes: [{ grapheme: 'an', exampleWord: 'maman' }, { grapheme: 'en', exampleWord: 'maman' }], order: 8, level: 'both' },
  { id: 'in', displaySymbol: 'in', graphemes: [{ grapheme: 'in', exampleWord: 'lapin' }, { grapheme: 'ien', exampleWord: 'chien' }], order: 9, level: 'both' },
  { id: 'oi', displaySymbol: 'oi', graphemes: [{ grapheme: 'oi', exampleWord: 'poisson' }], order: 10, level: 'both' },
  { id: 'eu', displaySymbol: 'eu', graphemes: [{ grapheme: 'eu', exampleWord: 'fleur' }], order: 11, level: 'both' },
  { id: 'b', displaySymbol: 'b', graphemes: [{ grapheme: 'b', exampleWord: 'ballon' }], order: 12, level: 'both' },
  { id: 'ch', displaySymbol: 'ch', graphemes: [{ grapheme: 'ch', exampleWord: 'chat' }], order: 13, level: 'both' },
  { id: 'd', displaySymbol: 'd', graphemes: [{ grapheme: 'd', exampleWord: 'domino' }], order: 14, level: 'both' },
  { id: 'f', displaySymbol: 'f', graphemes: [{ grapheme: 'f', exampleWord: 'fille' }], order: 15, level: 'both' },
  { id: 'g', displaySymbol: 'g', graphemes: [{ grapheme: 'g', exampleWord: 'gâteau' }], order: 16, level: 'both' },
  { id: 'j', displaySymbol: 'j', graphemes: [{ grapheme: 'j', exampleWord: 'jardin' }, { grapheme: 'ill', exampleWord: 'fille' }], order: 17, level: 'both' },
  { id: 'k', displaySymbol: 'k', graphemes: [{ grapheme: 'c', exampleWord: 'école' }, { grapheme: 'k', exampleWord: 'kangourou' }], order: 18, level: 'both' },
  { id: 'l', displaySymbol: 'l', graphemes: [{ grapheme: 'l', exampleWord: 'lion' }], order: 19, level: 'both' },
  { id: 'm', displaySymbol: 'm', graphemes: [{ grapheme: 'm', exampleWord: 'maman' }], order: 20, level: 'both' },
  { id: 'n', displaySymbol: 'n', graphemes: [{ grapheme: 'n', exampleWord: 'nid' }], order: 21, level: 'both' },
  { id: 'p', displaySymbol: 'p', graphemes: [{ grapheme: 'p', exampleWord: 'papa' }], order: 22, level: 'both' },
  { id: 'r', displaySymbol: 'r', graphemes: [{ grapheme: 'r', exampleWord: 'robot' }], order: 23, level: 'both' },
  { id: 's', displaySymbol: 's', graphemes: [{ grapheme: 's', exampleWord: 'souris' }, { grapheme: 'ss', exampleWord: 'poisson' }], order: 24, level: 'both' },
  { id: 't', displaySymbol: 't', graphemes: [{ grapheme: 't', exampleWord: 'table' }], order: 25, level: 'both' },
  { id: 'v', displaySymbol: 'v', graphemes: [{ grapheme: 'v', exampleWord: 'vélo' }], order: 26, level: 'both' },
  { id: 'z', displaySymbol: 'z', graphemes: [{ grapheme: 'z', exampleWord: 'oiseau' }, { grapheme: 's', exampleWord: 'maison' }], order: 27, level: 'both' },
  { id: 'gn', displaySymbol: 'gn', graphemes: [{ grapheme: 'gn', exampleWord: 'montagne' }], order: 28, level: 'both' },
]

export const sampleWords: WordEntry[] = [
  { word: 'chat', phonemes: ['ch', 'a'], frequency: 100, level: 1, category: 'nom' },
  { word: 'chats', phonemes: ['ch', 'a'], frequency: 40, level: 1, category: 'nom' },
  { word: 'chien', phonemes: ['ch', 'i', 'in'], frequency: 95, level: 1, category: 'nom' },
  { word: 'papa', phonemes: ['p', 'a', 'p', 'a'], frequency: 90, level: 1, category: 'nom' },
  { word: 'maman', phonemes: ['m', 'a', 'm', 'an'], frequency: 90, level: 1, category: 'nom' },
  { word: 'moto', phonemes: ['m', 'o', 't', 'o'], frequency: 60, level: 1, category: 'nom' },
  { word: 'vélo', phonemes: ['v', 'e', 'l', 'o'], frequency: 65, level: 1, category: 'nom' },
  { word: 'école', phonemes: ['e', 'k', 'o', 'l'], frequency: 85, level: 1, category: 'nom' },
  { word: 'ballon', phonemes: ['b', 'a', 'l', 'on'], frequency: 70, level: 1, category: 'nom' },
  { word: 'ballons', phonemes: ['b', 'a', 'l', 'on'], frequency: 30, level: 1, category: 'nom' },
  { word: 'bateau', phonemes: ['b', 'a', 't', 'o'], frequency: 55, level: 1, category: 'nom' },
  { word: 'oiseau', phonemes: ['oi', 'z', 'o'], frequency: 50, level: 1, category: 'nom' },
  { word: 'souris', phonemes: ['s', 'ou', 'r', 'i'], frequency: 45, level: 1, category: 'nom' },
  { word: 'tortue', phonemes: ['t', 'o', 'r', 't', 'u'], frequency: 40, level: 1, category: 'nom' },
  { word: 'lion', phonemes: ['l', 'i', 'on'], frequency: 50, level: 1, category: 'nom' },
  { word: 'lions', phonemes: ['l', 'i', 'on'], frequency: 20, level: 1, category: 'nom' },
  { word: 'poisson', phonemes: ['p', 'oi', 's', 'on'], frequency: 55, level: 1, category: 'nom' },
  { word: 'poissons', phonemes: ['p', 'oi', 's', 'on'], frequency: 25, level: 1, category: 'nom' },
  { word: 'table', phonemes: ['t', 'a', 'b', 'l'], frequency: 60, level: 1, category: 'nom' },
  { word: 'robot', phonemes: ['r', 'o', 'b', 'o'], frequency: 45, level: 1, category: 'nom' },
  { word: 'fille', phonemes: ['f', 'i', 'j'], frequency: 65, level: 1, category: 'nom' },
  { word: 'maison', phonemes: ['m', 'e', 'z', 'on'], frequency: 75, level: 1, category: 'nom' },
  { word: 'maisons', phonemes: ['m', 'e', 'z', 'on'], frequency: 25, level: 1, category: 'nom' },
  { word: 'gâteau', phonemes: ['g', 'a', 't', 'o'], frequency: 55, level: 1, category: 'nom' },
  { word: 'soleil', phonemes: ['s', 'o', 'l', 'e', 'j'], frequency: 50, level: 1, category: 'nom' },
  { word: 'lapin', phonemes: ['l', 'a', 'p', 'in'], frequency: 50, level: 1, category: 'nom' },
  { word: 'nid', phonemes: ['n', 'i'], frequency: 20, level: 1, category: 'nom' },
  { word: 'domino', phonemes: ['d', 'o', 'm', 'i', 'n', 'o'], frequency: 15, level: 1, category: 'nom' },
  { word: 'fleur', phonemes: ['f', 'l', 'eu', 'r'], frequency: 40, level: 1, category: 'nom' },
  { word: 'fleurs', phonemes: ['f', 'l', 'eu', 'r'], frequency: 20, level: 1, category: 'nom' },
  { word: 'montagne', phonemes: ['m', 'on', 't', 'a', 'gn'], frequency: 30, level: 1, category: 'nom' },
  { word: 'petit', phonemes: ['p', 'e', 't', 'i'], frequency: 60, level: 1, category: 'adjectif' },
  { word: 'petite', phonemes: ['p', 'e', 't', 'i', 't'], frequency: 55, level: 1, category: 'adjectif' },
  { word: 'joli', phonemes: ['j', 'o', 'l', 'i'], frequency: 45, level: 1, category: 'adjectif' },
  { word: 'jolie', phonemes: ['j', 'o', 'l', 'i'], frequency: 40, level: 1, category: 'adjectif' },
  { word: 'manger', phonemes: ['m', 'an', 'j', 'e'], frequency: 50, level: 1, category: 'verbe' },
  { word: 'sauter', phonemes: ['s', 'o', 't', 'e'], frequency: 35, level: 1, category: 'verbe' },
  { word: 'avec', phonemes: ['a', 'v', 'e', 'k'], frequency: 65, level: 1, category: 'invariable' },
]
